# https://taskfile.dev

version: '3'

tasks:
  default: task --list

  test:
    desc: Run the test suite for all packages and apps
    cmds:
      - uv run pytest packages/pdf-reader/tests/ -v
      - uv run pytest packages/xlsx-reader/tests/ -v
      - uv run pytest apps/backend/tests/ -v
      - uv run pytest apps/frontend/tests/ -v

  test:watch:
    desc: Run tests in watch mode (requires pytest-watcher)
    cmds:
      - uv run ptw -- packages/pdf-reader/tests/ packages/xlsx-reader/tests/ -v

  test:coverage:
    desc: Run tests with coverage report
    cmds:
      - uv run pytest packages/*/tests/ -v --cov=packages --cov-report=html --cov-report=term
