# https://taskfile.dev

version: '3'

tasks:
  default: task --list

  # Test tasks
  test:
    desc: Run all tests (packages, backend, and frontend)
    cmds:
      - $HOME/.local/bin/uv run pytest packages/pdf-reader/tests/ packages/xlsx-reader/tests/ apps/backend/tests/ apps/frontend/tests/ -v

  test:short:
    desc: Run all tests with short traceback (useful for CI/CD)
    cmds:
      - $HOME/.local/bin/uv run pytest packages/pdf-reader/tests/ packages/xlsx-reader/tests/ apps/backend/tests/ apps/frontend/tests/ -v --tb=short

  test:watch:
    desc: Run Python tests in watch mode
    cmds:
      - $HOME/.local/bin/uv run ptw -- packages/pdf-reader/tests/ packages/xlsx-reader/tests/ apps/backend/tests/ apps/frontend/tests/ -v

  test:coverage:
    desc: Run tests with coverage report
    cmds:
      - $HOME/.local/bin/uv run pytest packages/*/tests/ apps/backend/tests/ apps/frontend/tests/ -v --cov=packages --cov=apps/backend --cov-report=html --cov-report=term

  # Individual package tests
  test:pdf:
    desc: Run PDF reader tests only
    cmds:
      - $HOME/.local/bin/uv run pytest packages/pdf-reader/tests/ -v

  test:xlsx:
    desc: Run XLSX reader tests only
    cmds:
      - $HOME/.local/bin/uv run pytest packages/xlsx-reader/tests/ -v

  test:frontend:
    desc: Run frontend HTML validation tests only
    cmds:
      - $HOME/.local/bin/uv run pytest apps/frontend/tests/ -v

  test:e2e:
    desc: Run comprehensive E2E tests (requires browser dependencies and running server)
    cmds:
      - echo "Make sure frontend server is running: task frontend:dev"
      - $HOME/.local/bin/uv run pytest apps/frontend/tests/ -v -m e2e

  test:e2e:docker:
    desc: Run E2E tests in Docker with all dependencies
    cmds:
      - docker compose -f docker-compose.test.yml up --build --abort-on-container-exit
      - docker compose -f docker-compose.test.yml down

  test:sanity:
    desc: Run quick sanity checks on frontend (requires running server)
    cmds:
      - echo "Make sure frontend server is running: task frontend:dev"
      - $HOME/.local/bin/uv run pytest apps/frontend/tests/test_sanity.py -v

  test:sanity:docker:
    desc: Run sanity tests in Docker (no system dependencies needed)
    cmds:
      - docker compose -f docker-compose.test.yml up --build --abort-on-container-exit
      - docker compose -f docker-compose.test.yml down

  test:backend:
    desc: Run backend tests only
    dir: apps/backend
    cmds:
      - $HOME/.local/bin/uv run pytest -v

  # Backend tasks
  backend:dev:
    desc: Run backend dev server with auto-reload
    dir: apps/backend
    cmds:
      - $HOME/.local/bin/uv run uvicorn backend.main:app --reload

  # Frontend tasks (static HTML)
  frontend:dev:
    desc: Serve static HTML frontend with Python
    dir: apps/frontend
    cmds:
      - $HOME/.local/bin/uv run python -m http.server 8080

  frontend:open:
    desc: Open frontend in default browser
    cmds:
      - $HOME/.local/bin/uv run python -c "import webbrowser; webbrowser.open('http://localhost:8080')"
