# https://taskfile.dev

version: '3'

tasks:
  default: task --list

  test:
    desc: Run all tests (Python packages and backend)
    cmds:
      - uv run pytest packages/pdf-reader/tests/ -v
      - uv run pytest packages/xlsx-reader/tests/ -v
      - uv run pytest apps/backend/tests/ -v

  test:watch:
    desc: Run Python tests in watch mode
    cmds:
      - uv run ptw -- packages/pdf-reader/tests/ packages/xlsx-reader/tests/ apps/backend/tests/ -v

  test:coverage:
    desc: Run tests with coverage report
    cmds:
      - uv run pytest packages/*/tests/ apps/backend/tests/ -v --cov=packages --cov=apps/backend --cov-report=html --cov-report=term

  # Backend tasks
  backend:dev:
    desc: Run backend dev server with auto-reload
    dir: apps/backend
    cmds:
      - uv run uvicorn backend.main:app --reload

  backend:test:
    desc: Run backend tests
    dir: apps/backend
    cmds:
      - uv run pytest -v

  # Frontend tasks (npm-based)
  frontend:install:
    desc: Install frontend dependencies
    dir: apps/frontend
    cmds:
      - npm install

  frontend:dev:
    desc: Run frontend dev server
    dir: apps/frontend
    cmds:
      - npm run dev

  frontend:build:
    desc: Build frontend for production
    dir: apps/frontend
    cmds:
      - npm run build

  frontend:test:
    desc: Run frontend tests
    dir: apps/frontend
    cmds:
      - npm run test
